### ISSUE TITLE
VerifyAdd does not work

### ISSUE THREAD

**Issue by apazureck** [devlooped/moq#1099]
Hi,

First of all thanks for this great framework, having a lot of fun using it!

I stumbled upon a problem with verifying add. I currently use the nuget version 4.14.7

`<PackageReference Include="Moq" Version="4.14.7" />`

The target framework is .net core 3.1

I tried following test:

```csharp
public class MyTestClass
{
    [Fact]
    public void TestMoq() 
    {
        
            Mock<MoqTestInterface> ti = new Mock<MoqTestInterface>();

            object o = null;

            ti.Object.TestEvent += obj => o = obj;

            ti.VerifyAdd(t => t.TestEvent += It.IsAny<TestDelegate>(), Times.Once());
        }
    }

    public delegate void TestDelegate(object input);

    public interface MoqTestInterface
    {
        event TestDelegate TestEvent;
    }
```

I would expect this to pass, because it was subscribed once, but my Test tells me it was not called.

What am I doing wrong?

Cheers!

**Comment by stakx** [comment]
You're doing nothing wrong, it's just that for back-compatibility reasons, `VerifyAdd` required at least one prior call to `SetupAdd` / `SetupRemove` on the same mock. (See #1058.) This requirement has recently been lifted by #1082 and your use case should work in the upcoming release (4.15.0).

**Comment by apazureck** [comment]
Thanks for the quick reply. Worked like a charm. Ok, now I get why me/google did not find anything on that topic.
