### ISSUE TITLE
Hi There, I just updated Moq package from version 4.14.7 to version 4.15.1 and noticed that it broke Unit Tests for my projects. Kindly look into this matter. Thanks in advance, Regards, Asheesh Agrawal

### ISSUE THREAD

**Issue by asheeshgrwll** [devlooped/moq#1103]
Hi There, I just updated Moq package from version 4.14.7 to version 4.15.1 and noticed that it broke Unit Tests for my projects. Kindly look into this matter. 
Thanks in advance.
Regards, 
Asheesh Agrawal

**Comment by stakx** [comment]
I left my crystal ball at home, so you'll need to be more specific and provide a minimal repro.
