### ISSUE TITLE
[FEATURE REQUEST] Implicit Type Casting from Mock to Object?

### ISSUE THREAD

**Issue by mathew-odwyer** [devlooped/moq#1105]
I always find myself doing something like the following:

```csharp
var foo = new Mock<IFoo>();
var bar = new Bar(foo);
```

and then realizing I have to change `foo` to `foo.Object` in `Bar`'s constructor. Personally, I think it would be a great idea to allow implicit casting from `Mock<IFoo>` to `IFoo` 😸

**Comment by stakx** [comment]
Duplicate of #1097. See there for an explanation why this won't work.
