### ISSUE TITLE
Adding a setup looks like it became an O(n*n) operation since #984 was merged

### ISSUE THREAD

**Issue by CeesKaas** [devlooped/moq#1110]
I don't think this will be an issue for many users but in one of our tests we added 3000 setups to a mock and after updating from 4.13.1 to 4.15.2 the test time went from <10 seconds to over 14 minutes

**Comment by stakx** [comment]
What led you to the assumption that this slowdown was caused by #984, if I may ask? Understanding this might help looking into that matter.

**Comment by CeesKaas** [comment]
in public void Add(Setup setup) of SetupCollection the call this.MarkOverriddenSetups(); was added

that method loops through all items already in the SetupCollection

**Comment by CeesKaas** [comment]
for a very basic reproduction i used :
```
using System;
using System.Diagnostics;
using Moq;

namespace moq_repro
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"{DateTime.Now:o} Start");
            var sw = Stopwatch.StartNew();
            var mock = new Mock<ITestInterface>();
            for (int i = 0; i < 3000; i++)
            {
                mock.Setup(m=>m.Get(Guid.NewGuid()));
            }
            sw.Stop();
            Console.WriteLine($"{DateTime.Now:o} Finish (took:{sw.Elapsed})");
        }
    }
    public interface ITestInterface{
        void Get(Guid id);
    }
}
```
with Moq version 4.13.1 this program takes 273ms (on my machine)
with Moq version 4.14.0 it takes 6:28 minutes

**Comment by stakx** [comment]
OK thanks. I'll look into it.

> the call this.MarkOverriddenSetups(); was added
>
> that method loops through all items already in the SetupCollection

Wouldn't that make it 2n (as opposed to n<sup>2</sup>)?

**Comment by CeesKaas** [comment]
you could be correct i'm not fully up to speed with the big O notation i had 2 loops in my mind (the for loop around the call to setup and the for loop in MarkOverriddenSetups) so the setup add went from O(1) to O(n) probably

**Comment by CeesKaas** [comment]
I've create PR #1111 with a potential fix
