### ISSUE TITLE
TypeNotMockable Exception

### ISSUE THREAD

**Issue by Sergeir1** [devlooped/moq#1112]
Can the Moq Gaurd class exception below also return the type name? it would be very helpful when mocking objects that take multiple constructor parameters.

		public static void IsMockable(Type type)
		{
			if (!type.IsMockable())
			{
				throw new NotSupportedException(Resources.TypeNotMockable);
			}
		}

**Comment by stakx** [comment]
Doesn't the stack trace already point at the code location where you're trying to instantiate a mock?

But yes, I suppose we could do that. Feel free to submit a PR.
