### ISSUE TITLE
NuDoq API documentation seems broken

### ISSUE THREAD

**Issue by computamike** [devlooped/moq#1146]
the nudoc site linke (http://www.nudoq.org/#!/Projects/Moq) page seems broken.

![image](https://user-images.githubusercontent.com/464876/109733017-32b63b80-7bb6-11eb-89a6-2fbfbfe1fbf0.png)

Searching for moq returns no results.

**Comment by stakx** [comment]
Yep, that's a well-known problem; see #1090, #1086, #1023, #354.

**Comment by stakx** [comment]
NuDoq has been down and/or going stale for so long now that I think it makes sense to remove the link to it from `README.md`.

**Comment by stakx** [comment]
Done in 534b5cdec62b43fde5e8cd23fd9d1431aa2ea57a. We'll eventually need to suggest a new place where to find documentation (including API reference docs) once we have set that up (see e.g. #1090).
