### ISSUE TITLE
ProtectedAsMock issues

### ISSUE THREAD

**Issue by tonyhallett** [devlooped/moq#1162]
Does not work with auto mocking
![image](https://user-images.githubusercontent.com/11292998/120066401-0ce1eb00-c06e-11eb-8f9c-32201f27e095.png)
Due to https://github.com/moq/moq4/blob/a6fde8b6d79a7437bf642d115785b97f40779b6a/src/Moq/Protected/ProtectedAsMock.cs#L233

Does not work with virtual properties. ArgumentException
https://github.com/moq/moq4/blob/a6fde8b6d79a7437bf642d115785b97f40779b6a/src/Moq/Protected/ProtectedAsMock.cs#L289

**Comment by stakx** [comment]
Could you please post a minimal, complete & verifiable repro demonstrating a use case where this error gets triggered? So that we know why we need a bugfix, and what exactly it is fixing. Thanks.

**Comment by tonyhallett** [comment]
You can use the tests in my pull request that throw without the fix.

**Comment by tonyhallett** [comment]
To be precise

https://github.com/moq/moq4/blob/641821678a630e4d9a19bd883b6be4cafd5d56eb/tests/Moq.Tests/ProtectedAsMockFixture.cs#L154
https://github.com/moq/moq4/blob/641821678a630e4d9a19bd883b6be4cafd5d56eb/tests/Moq.Tests/ProtectedAsMockFixture.cs#L163

**Comment by tonyhallett** [comment]
@stakx repro provided.  These tests fail currently.  Fixed with #1163 
```
public class ProtectedAsMockFixture
{
	private Mock<Foo> mock;
	private IProtectedAsMock<Foo, Fooish> protectedMock;

	public ProtectedAsMockFixture()
	{
		this.mock = new Mock<Foo>();
		this.protectedMock = this.mock.Protected().As<Fooish>();
	}

        [Fact]
        public void SetUpGet_can_automock()
        {
	        this.protectedMock.SetupGet(m => m.Nested.Value).Returns(42);

	        var actual = mock.Object.GetNested().Value;

	        Assert.Equal(42, actual);
        }

       [Fact] 
       void SetupGet_can_setup_virtual_property()
       {
	       this.protectedMock.SetupGet(m => m.Virtual).Returns(42);

	       var actual = mock.Object.GetVirtual();

	       Assert.Equal(42, actual);
        }
}

public interface INested
{
	int Value { get; }
}

public abstract class Foo
{
	protected abstract INested Nested { get; set; }

	public INested GetNested()
	{
		return Nested;
	}

	private int virtualProperty;
	public virtual int Virtual
	{
		protected get
		{
			return virtualProperty;
		}
		set
		{
			virtualProperty = value;
		}

	}

	public int GetVirtual()
	{
		return Virtual;
	}
}

public interface Fooish
{
	INested Nested { get; set; }
	int Virtual { get; set; }
}

```

**Comment by tonyhallett** [comment]
Also fails for methods.

Adding method to INested
``
public interface INested
{
	int Value { get; }
	int Method(int value);
}

// This fails

[Fact]
public void Setup_can_automock()
{
	this.protectedMock.Setup(m => m.Nested.Method(1)).Returns(123);
	Assert.Equal(123, mock.Object.GetNested().Method(1));
}
``

Fixed with pull request

**Comment by stakx** [comment]
@tonyhallett, my apologies if I appear a little dense regarding your issues and PRs. I simply haven't yet found the time to study them all in detail; if I had, perhaps I wouldn't have been quite as confused with my review comments. It's slowly coming together now. Thanks for being patient. :-D
