### ISSUE TITLE
Mock.Verify susceptible to reference type alterations

### ISSUE THREAD

**Issue by marnu123** [devlooped/moq#1187]
Hello!

Firstly, great tool!  It's really helped me a lot so far, and I never go a day without it.

Summary:
When using reference types as parameters to mocked methods, and altering internal variables of parameter, calling Mock.Verify on the method can fail, because Mock stores the reference to the parameter, and not a copy of it.

Code setup:
```csharp
private class Person
{
    public string Name { get; set; }
    public string Surname { get; set; }
}

public interface IApi
{
    void Add(object obj);
}

[Fact]
public void Test()
{
    var obj = new Person() {Name = "Name", Surname = "Surname"};
    var mock = new Mock<IApi>();
    var mockedObject = mock.Object;
    mockedObject.Add(obj);

    obj.Name = "Shaun";
    
    // Name, in this case is equal to "Shaun"
    // Verification fails because the "Name" properties differ
    mock.Verify(e => e.Add(new Person() {Name = "Name", Surname = "Surname"}), Times.Once);
}
```

Expected outcome:
The verification should succeed, even though the object changed.  I expect that the parameters that were passed be deep cloned  to be used for verification

Current outcome:
Verification fails

Moq version: 4.16.1

**Comment by stakx** [comment]
We get this report all the time. I'll let you use the search facility to find similar issues (along with my responses), I'll just say here that this behavior is by design (the usual .NET equality semantics apply) and it won't be changed.

**Comment by marnu123** [comment]
Perfect, thanks!  Then I know what to do.  I see one similar "issue" was reported and closed recently, so sorry about that. I'm not used to Github's structure yet, coming from an Azure DevOps background

**Comment by stakx** [comment]
If anyone finds this issue and is experiencing the same problem, please see #1319; the last code example in the PR description shows a way how to solve this.
