### ISSUE TITLE
Add README to NuGet package

### ISSUE THREAD

**Issue by loic-sharma** [devlooped/moq#1194]
Hello!

I am from the NuGet team at Microsoft. We recently introduced support for embedding READMEs into NuGet packages ([blog](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/), [docs](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)), and we plan to place these READMEs front and center on nuget.org. Would you be willing to accept a contribution to add an embedded READMEs to the Moq package?

**Comment by stakx** [comment]
Hi @loic-sharma. Sounds great!

One thing, Moq packages are potentially released from two different repositories: this one here (moq/moq4), and [moq/moq](https://github.com/moq/moq). I suppose the `README.md` from the package last pushed "wins"? Or the one from the latest version?

We'd need to make sure that if we actually _do_ publish from both repositories, the _Readme_ section on NuGet won't randomly change.

/cc @kzu (for the moq/moq repo)

**Comment by loic-sharma** [comment]
Oh I didn't know y'all were working on a new version of Moq! READMEs are version-specific. In other words, if V4 has README `foo` and V5 has README `bar`, we will show `foo` if you browse V4 and `bar` if you browse V5. I'll send pull requests to both repositories! :)

**Comment by stakx** [comment]
I see, and since NuGet displays the latest version by default, one would typically see the `bar` README once Moq v5 has been officially released. Makes sense! :+1:

**Comment by stakx** [comment]
I'm closing this issue as it has gone stale. @loic-sharma (or anyone else), if you're still interested in adding a README to the Moq NuGet package, feel free to submit a PR.
