### ISSUE TITLE
`mock.Protected()` does not support methods with ref or out parameters

### ISSUE THREAD

**Issue by tonyhallett** [devlooped/moq#1195]
```
public class HasMethodWithRefParameter
{
	protected virtual void RefMethod(ref int arg) { }
}

[Fact]
public void ProtectedMockDoesNotSupportMethodsWithRefOrOutParameters()
{
	var mock = new Mock<HasMethodWithRefParameter>();
	
       // System.ArgumentException : No protected method HasMethodWithRefParameter.RefMethod found whose signature is compatible with the provided arguments (int).
        mock.Protected().Setup("RefMethod", 1);		
}

```

and this is not allowed 

```
int refInt = 1;
mock.Protected().Setup("RefMethod", ref refInt);
```

**Comment by stakx** [comment]
Uh, the method is called `RefMethod`, so the error message is actually expected behaviour...?

**Comment by tonyhallett** [comment]
Indeed !
Example updated.

**Comment by stakx** [comment]
Finally got some time to look at this. Sorry for the delay.

To be entirely honest, I don't see any value in any further additions to the `mock.Protected()` APIs. The whole point of adding `mock.Protected().As<>()` back in version 4.8.0 was to offer a typed alternative that worked just like the regular `mock.Setup` API as much as possible, i.e. to obviate the need to come up with alternate untyped APIs in `mock.Protected()`.

In my eyes, `mock.Protected().As<>()` is the way forward re: protected stuff. And even there, I'm cautious about any further additions. Testing protected type members doesn't seem like a terribly good idea to me, and I don't think Moq should much encourage that practice.

I am happy to see existing bugs in `mock.Protected()` fixed, and to fill in certain obvious gaps that have long been marked as `TODO`s (such as support for indexers). However, I don't think we should add any totally new concepts / public types to that part of Moq.

**Comment by tonyhallett** [comment]
> In my eyes, mock.Protected().As<>() is the way forward re: protected stuff. 

In my eyes too.  I have just been filling in what is missing in `mock.Protected()`.

If what is currently not possible is not going to be made possible I personally would update the readme to mention that out/ref setups and verification cannot be achieved with `mock.Protected()` and to use `mock.Protected().As<>`.

**Comment by stakx** [comment]
Glad to hear you agree!

>  I personally would update the readme to mention that out/ref setups and verification cannot be achieved with `mock.Protected()` and to use `mock.Protected().As<>`.

Good suggestion, though I'm not sure the `README.md` would be quite the right place for that cue, as it mostly gives a high-level overview of Moq. More detailed instructions currently live in the quickstart wiki page. Feel free to update it!

(We really ought to do something about Moq's documentation... 😄)

I'm going to close this (and the PR, too) as "won't fix". If I've missed anything, let me know.
