### ISSUE TITLE
Moq 4.16.1 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by seilorjunior** [devlooped/moq#1212]
Hello,

There is any plan to support dotnetcore?

The same build on my machine works.
But on my build server, i am getting this
Package Moq 4.16.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Moq 4.16.1 supports:
      - net45 (.NETFramework,Version=v4.5)
      - netstandard2.0 (.NETStandard,Version=v2.0)
      - netstandard2.1 (.NETStandard,Version=v2.1)

**Comment by stakx** [comment]
.NET Core 3.1 does implement .NET Standard 2, and so Moq does support .NET Core via that. Must be a problem with your build server setup or project.

**Comment by seilorjunior** [comment]
@stakx this issue only happens with nuget restore. I have resolved using dotnet restore. FYI
