### ISSUE TITLE
Broken assertion after upgrading from 4.2 to 4.16 with collection - BeEmpty()/HaveCount()

### ISSUE THREAD

**Issue by fforjan** [devlooped/moq#1213]
While migrating moq 4.2 to 4.16 ,we have encountered issues were the code does not compile anymore.
Some would be 'ok', WhichValue/WhoseValue, etc...

But we have a set which doesn't make sense, in particular :
![image](https://user-images.githubusercontent.com/601810/138156847-861c3b3c-488e-417f-81f4-1290c68137f8.png)

The collection in this sample being https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.uielementcollection?view=netframework-4.7.2

**Comment by stakx** [comment]
I don't see what this has to do with Moq. Closing.

**Comment by fforjan** [comment]
yeah, my bad. my very bad
