### ISSUE TITLE
It.IsSubtype<T> doesn't work when T has constraints 

### ISSUE THREAD

**Issue by CoenraadS** [devlooped/moq#1215]
I was struggling with the documentation for It.IsSubType 

https://stackoverflow.com/questions/69800011/moq-it-issubtype-has-no-implicit-reference-conversion/69800795#69800795

Until someone pointed me to use TypeMatcher instead. Perhaps it would be useful to include this part of the documentation: https://github.com/Moq/moq4/wiki/Quickstart#type-matchers-moq-413

**Comment by stakx** [comment]
@CoenraadS, feel free to edit the wiki. Adding `<remarks>` to the XML doc comments of [`It.IsSubtype<>`](https://github.com/moq/moq4/blob/e9fff47be6a7ce63c569fe49728df3c9cbc2b7a5/src/Moq/It.cs#L388) might be a nice addition, too.
