### ISSUE TITLE
How to tell if certain object is mocked by Moq

### ISSUE THREAD

**Issue by iamdmitrij** [devlooped/moq#1218]
Is there a way to tell if certain `object` instance is mocked by `Moq`?

There is `Mock.Get<T>()` static method but it does require generic type. All I need to tell is object by mocked.

Code like this will result in `ArgumentException`:

```
var mock = Mock.Of<IMockable>();
Mock.Get(mock as object);
```

One idea came to mind to use `ProxyUtil` from `Castle Dynamic Proxy`:

```
var isMock = ProxyUtil.IsProxy(targetObject);
```

Perhaps this is niche use-case for most of users and probably this shouldn't be a public part of `Moq`, but perhaps you have some ideas how to best implement it?

**Comment by stakx** [comment]
`obj is Moq.IMock`?

**Comment by iamdmitrij** [comment]
> `obj is Moq.IMock`?

As far I understand `IMock<out T> where T : class` requires a generic parameter T. Unfortunately, in my case `obj` is not statically typed. During runtime I only get mocked **Object** constructed from `new Mock<IMockable>().Object` and only then I need to check if `object` was mocked by `Moq`.

   Name | Value | Type
-- | -- | --
targetObject.GetType() | {Name = "IMockableProxy" FullName = "Castle.Proxies.IMockableProxy"} | System.Type {System.RuntimeType}

Utility function which I mentioned before does the trick `ProxyUtil.IsProxy(targetObject);`, however there would be false positives here, since there is no guarantee that it was exclusively mocked by `Moq`.

**Comment by stakx** [comment]
Apologies, I meant `Moq.IMocked`, not `Moq.IMock<>`.

And yes, while it is certainly possible that some party other than Moq itself could implement `IMocked`... why would they? I'd say that in real world scenarios, you should be able to rely on a `obj is IMocked` check.

**Comment by stakx** [comment]
I'm going to close this issue. There is no way to check whether an object was created by Moq, and Moq only. Your best bet is checking whether an object implements `IMocked`.
