### ISSUE TITLE
Verify() succeeds if there are no verifiable setups

### ISSUE THREAD

**Issue by rkm** [devlooped/moq#1222]
I was debugging a test which had a false positive result, and noticed that we had missed the `.Verifiable()` call for a setup. This was confusing since we were calling `.Verify()` at the end, so everything appeared fine at a first glance.

A cut-down example is:
```cs
public void CreateFile(IFileInfo fi) => fi.Create();

[Test]
public void Test()
{            
    var mockFile = new Mock<IFileInfo>();

    mockFile.Setup(x => x.Create());

    // Test stuff...
    // CreateFile(mockFile.Object);

    mockFile.Verify();
}
```

This passes, even though `CreateFile` is never called.

I may be misunderstanding the intended usage, but are there genuine situations where a call to `Verify()` (specifically the overload with no parameters) is valid even though there is nothing to verify?

Thanks!

**Comment by stakx** [comment]
Hi @rkm. I've been very busy, sorry for replying late.

I didn't originally create Moq so I can only speculate. I think the idea behind `.Verify()` only taking into account setups that have been marked as `.Verifiable()` was that sometimes you need some setups in order for the mock to behave in a certain way, but those may not be directly related or relevant to what you're going to verify, so there needed to be some way of distinguishing which ones are relevant, and which ones aren't.

However it may be, there's an easy solution: use `.VerifyAll()` instead.
