### ISSUE TITLE
Setup with generic args not retrieving explicitly registered interface when the base interface is setup later

### ISSUE THREAD

**Issue by chigeroo** [devlooped/moq#1224]
Hi.  I have just upgraded from Moq 4.2.1510.2205 to Moq 4.16.1 and am getting failing tests in the following scenario which previously worked fine.  I have provided a failing test and a successful test:

```
public class GenericMethodRegistrationOrder
    {
        [Test]
        public void This_test_is_failing_thows_an_exception()
        {
            var mockInterfaceRetriever = new Mock<IInterfaceRetriever>();

            var mockA = new Mock<IInterfaceDerivedA>();
            var mockB = new Mock<IInterfaceDerivedB>();

            // When resolving IInterfaceDerivedB, it is still trying to take the registration for IInterfaceBase and cast it to IInterfaceDerivedB even though there is an explicit registration for IInterfaceDerivedB
            mockInterfaceRetriever.Setup(s => s.GetSomeInterface<IInterfaceDerivedB>()).Returns(mockB.Object);
            mockInterfaceRetriever.Setup(s => s.GetSomeInterface<IInterfaceBase>())
                .Returns(mockA.Object);

            ClassToTest classToTest = new ClassToTest(mockInterfaceRetriever.Object);
            classToTest.DoSomething();
        }

        [Test]
        public void This_test_succeeds_when_setup_is_done_in_order_of_base_first_then_derived()
        {
            var mockInterfaceRetriever = new Mock<IInterfaceRetriever>();

            var mockA = new Mock<IInterfaceDerivedA>();
            var mockB = new Mock<IInterfaceDerivedB>();
            mockInterfaceRetriever.Setup(s => s.GetSomeInterface<IInterfaceBase>())
                .Returns(mockA.Object);
            mockInterfaceRetriever.Setup(s => s.GetSomeInterface<IInterfaceDerivedB>()).Returns(mockB.Object);

            ClassToTest classToTest = new ClassToTest(mockInterfaceRetriever.Object);
            classToTest.DoSomething();
        }
    }

    public class ClassToTest
    {
        private readonly IInterfaceRetriever _retriever;

        public ClassToTest(IInterfaceRetriever retriever)
        {
            _retriever = retriever;
        }

        public void DoSomething()
        {
            _retriever.GetSomeInterface<IInterfaceBase>();
            _retriever.GetSomeInterface<IInterfaceDerivedB>();
        }
    }

    public interface IInterfaceRetriever
    {
        T GetSomeInterface<T>() where T : IInterfaceBase;
    }

    public interface IInterfaceBase
    {
    }

    public interface IInterfaceDerivedA : IInterfaceBase
    {

    }

    public interface IInterfaceDerivedB : IInterfaceBase
    {

    }
```

Expected outcome:
_retriever.GetSomeInterface<IInterfaceDerivedB>(); should return an IInterfaceDerivedB

Incorrect outcome:
The failing test is occurring because it is resolving to the base interface registration instead of the specific one so _retriever.GetSomeInterface<IInterfaceDerivedB>(); is trying to get IInterfaceBase from Moq and therefore throws the following exception:

System.InvalidCastException : Unable to cast object of type 'Castle.Proxies.IInterfaceDerivedAProxy' to type 'MoqBug.IInterfaceDerivedB'.
   at Castle.Proxies.IInterfaceRetrieverProxy.GetSomeInterface[T]()
   at MoqBug.ClassToTest.DoSomething() in C:\Users\chirag.sawjani\source\repos\ConsoleApp1\MoqBug\GenericMethodRegistrationOrder.cs:line 53
   at MoqBug.GenericMethodRegistrationOrder.This_test_is_failing_throwing_an_exception() in C:\Users\chirag.sawjani\source\repos\ConsoleApp1\MoqBug\GenericMethodRegistrationOrder.cs:line 22

The same thing will happen even if you register mockA as follows 
`var mockA = new Mock<IInterfaceBase>();`

**Comment by rjvdboon** [comment]
When I had the same error in one of my tests after updating to Moq 4.16.1. It helped to reverse the order of registration (the more Base before the more Derived). Search the other issues for background, that's where I got the idea from.

**Comment by stakx** [comment]
Yes, always order your setups from most general (least specific) to most specific; that is, base types before subtypes, `It.IsAny<>` before more specific argument values, etc.
