### ISSUE TITLE
Moq.Verify cant detect Invocation when a method is passed

### ISSUE THREAD

**Issue by evilc0** [devlooped/moq#1225]
Hello,

first of all, thank you very much for this masterpeace of software.

I think i found a bug in the verification of mocks, i assume that it is coming from late time binding of parameter invocation, but its just a assumtation.

`Moq.Verify(m => m.MyMethod(Convert.FromBase64String(myArr)) wont match.`

```
Moq.MockException : 
Expected invocation on the mock at least once, but was never performed: m => m.Transmit(1, [1, 2, 3], It.IsAny<byte[]>())

Performed invocations:

   Mock<IHardware:3> (m):

      IHardware.Transmit(1, [1, 2, 3], [0, 0, 0, 0, 0, 0, 0, 0])
```

I've created a minimal repo to reproduce the problem:

https://github.com/evilc0/MoqBug

**Comment by stakx** [comment]
Hi @evilc0, I've taken a look. There is indeed an inconsistency in how Moq matches enumerable values (such as your `byte[]` arrays), depending on whether they are passed directly (as a constant) or returned from a method call. The PR linked above should rectify this.
