### ISSUE TITLE
Unexpected resolution of extension method against Mock<T>

### ISSUE THREAD

**Issue by aaronburro** [devlooped/moq#1245]
Moq Version: 4.2.1502.911 (need to check newer version against this...)
.NET Version: Framework 4.5.2
VS: VS 2017
Test Runner: ReSharper 2019.1

I had a unit test failure caused by Mock<T>.Object failing to use the appropriate extension method in an overload situation. See the below code for example.

```
public interface IFoo<T> { DoIt(params T[] items); }
public static class FooExtensions { public static void DoIt<T>(this IFoo<T> instance, IEnumerable<T> items) { instance?.DoIt(items?.ToArray()); } }

[TestFixture]
public class Tests
{
    [Test]
    public void Test_Null([Values] bool explicitCall)
    {
        var mock = new Mock<IFoo<object>>();
        mock.Setup(m => m.DoIt(It.IsAny<object[]>())).Callback((object[] c) => Assert.IsNull(c));

        if (explicitCall) FooExtensions.DoIt(mock.Object, default(IEnumerable<object>));    // this succeeds!
        else mock.Object.DoIt(default(IEnumerable<object>));                                // this fails!
    }
}
```

**Comment by stakx** [comment]
I don't think this has anything to do with Moq, but with the C# language and compiler themselves. If you inspect the IL generated for the statement `mock.Object.DoIt(default(IEnumerable<object>));`  by the compiler, you'll get this:

```
// mock.Object.DoIt(null);
ldloc.0
callvirt instance !0 class [Moq]Moq.Mock`1<class IFoo`1<object>>::get_Object()
ldc.i4.1
newarr [System.Runtime]System.Object
callvirt instance void class IFoo`1<object>::DoIt(!0[])
```

Note that it only looks like you're passing a single `null` reference, but in reality, due to the `params` in the method signature, you're actually passing a `new object[1]` (whose first and only element is equal to `null`).

**Comment by aaronburro** [comment]
I don't doubt that is the IL generated under the hood, since that is what was called. The question I would have is why a method whose signature clearly calls for an array got matched to a call which provided an IEnumerable (with no chance to be an array).

I can dig deeper, but this is a fairly normal pattern we use, and I've only ever seen it fail so far with an Moq Mock.

**Comment by aaronburro** [comment]
So, I was confused initially, but this is why you don't write tests so late. It seems the overload resolution gives precedence to instance methods over extension methods (makes sense) if it can *possibly* fit, and in this case, now that I'm thinking clearer, it's obvious it considered the item as an object instead of `IEnumerable<object>`. Adding a seemingly pointless as cast makes it pick the right one. Using object isn't a normal use case for the actual class, so that's why you only see it in the test. If I did `string`, it'd be no problem.

Late night coding is the best.
