### ISSUE TITLE
Unable to call base interface getter with cast without explicit setup.

### ISSUE THREAD

**Issue by gurustron** [devlooped/moq#1254]
public interface IQueryModel : IQueryModelImmutable
    {
        public int Property1 { get; set; } 
    }

    public interface IQueryModelImmutable
    {
        public int Property1 { get; } 
    }

    Mock<IQueryModel> mock = new Mock<IQueryModel>
    {
        // CallBase = true // does not affect things, can be commented in/out
    };
    // mock.Setup(m => m.Property1).Returns(100);
    mock.As<IQueryModelImmutable>().Setup(m => m.Property1).Returns(100); // works only if both setups are present
    IQueryModelImmutable toTest = mock.Object;
    Assert.AreEqual(100, mock.Object.Property1);
    Assert.AreEqual(100, toTest.Property1);

Tried different combinations of setting up only one of interfaces and using/ not using `CallBase` - only working one is when both interfaces `get_Property1` is set up explicitly.

**Comment by stakx** [comment]
`CallBase` has no effect in this case because there is no base implementation to call; all your interfaces' members are abstract.

If you implemented those interfaces yourself, you wouldn't try to invoke `base.Property1`, right?

**Comment by gurustron** [comment]
@stakx it's not about `CallBase`. If you remove it still setting up both methods is needed. Casting to base interface is not working otherwise.

If I've implemented both those interfaces in one class - casting it to base interface would have worked.

**Comment by gurustron** [comment]
@stakx ?

**Comment by stakx** [comment]
I don't get it. If it' not about `CallBase`, why is it mentioned everywhere, including in your question title? I suggest you rephrase the whole thing and remove whatever isn't actually related to your issue.
