### ISSUE TITLE
sealed method mock calls actual method instead of mocked

### ISSUE THREAD

**Issue by LogunovAV** [devlooped/moq#1255]
if you Mock the method of the class which has sealed identifier, the mock.Object.Method will call an actual method, not the mocked one.

**Comment by AlexRuMath** [comment]
> if you Mock the method of the class which has sealed identifier, the mock.Object.Method will call an actual method, not the mocked one.
Example:
![MockRunTransaction](https://user-images.githubusercontent.com/49819578/166982103-ea265075-a743-4e92-9fb8-c1653c761571.png)
![MockSwaled](https://user-images.githubusercontent.com/49819578/166982105-1b3c5330-64ed-475b-86f3-02721b58c0bd.png)

**Comment by stakx** [comment]
Moq doesn't support sealed classes/methods. You can only mock non-sealed types and virtual, non-sealed methods.
