### ISSUE TITLE
Add primitive for It.IsAny

### ISSUE THREAD

**Issue by niksanla2** [devlooped/moq#1268]
I think it will be more conveniently if we just add for primitive types something like:
It.IsAnyString()
It.IsAnyInt()
It.IsAnyDouble()
It.IsAnyBool()
etc.

**Comment by stakx** [comment]
I don't think this is worth the effort. For starters, in C#, `It.IsAnyInt()` isn't much shorter than `It.IsAny<int>()`. If we added those as "shortcuts", they should be at least be properties so you don't need to type the parentheses: `It.IsAnyInt`. But there are other potential issues, e.g.:

* The suggested member names use C# type names. Perhaps the majority of .NET users use C#, but it's not the only language. (Note how Moq's XML doc comments often mention VB.NET alongside C#.) For VB.NET, one may expect different member names, e.g. `It.IsAnyInteger`. Or, if we made this language-agnostic, we might prefer BCL / CLS type names, e.g. `It.IsAnyInt32`. I would personally also prefer the C# names but that may just be that, a preference.

* People requesting more and more shortcut methods for other BCL types. Where will we draw the line?

* Overloading IntelliSense / code completion. `It.IsAny<>()` is perhaps by far the most important argument matcher, and having a lot of other `It.IsAny...` methods might make it more difficult to select it from code completion lists.

* More code to maintain in general.

I don't think the rather tiny benefit of those shortcuts (saving two keystrokes per matcher usage) are worth the hassle.
