### ISSUE TITLE
Performance Issues After Version 4.12.0

### ISSUE THREAD

**Issue by asherjvitek** [devlooped/moq#1269]
Recently we updated our version of moq from 4.7.99 to 4.17.2 in the Solution we use which has around 12,000 unit tests. When we did this the Test run times jumped from around 3+ minutes to 12+ minutes. Once this was noticed we did some benchmarking on a subset of 54 of those unit test and found the following performance differences.

| MOQ Version | Time |
| --- | --- |
| 4.7.99 | 2.7sec |
| 4.8.0 | 1.1sec |
| 4.9.0 | 1.1sec |
| 4.10.0 | 1.1sec |
| 4.11.0 | 979ms |
| 4.12.0 | 959ms |
| 4.13.0 | 10.3sec |
| 4.15.1 | 10.5sec |
| 4.17.2 | 10.5sec |

It would appear that after at version 4.13.0 there is a large slow down in the time it takes to run our unit tests. 

I found [this issue](https://github.com/moq/moq4/issues/1083#issuecomment-717396028) and the comment in the last bullet point seems to be exactly what I am seeing but I feel like a performance hit like this seems a little too large.

Is this performance hit to be expected in newer versions? 

If you need a sample of the tests I would need to extract and change the code as it is proprietary to the company I work for but is something I should be able to do if it is necessary. 

Please let me know and thank you.

**Comment by stakx** [comment]
> If you need a sample of the tests I would need to extract and change the code

Yes, if you want someone looking into this, repro code will be required. Otherwise there isn't much that can be done.

**Comment by stakx** [comment]
@asherjvitek, any chance that you could provide a test case that I could use to re-run those runtime measurements / reproduce the performance degradation starting in version 4.13.0?

Otherwise I'm going to close this issue in about two weeks' time.

**Comment by asherjvitek** [comment]
I'm really sorry, I meant to update this issue.

I tried building up an example that didn't use any proprietary code and
when I did the performance difference was not nearly as noticable.

It appears that mocking a large COM Interop object is at the core of the
issue in the codebase I work in.

With that being said I can't give an example including that Interop.

You can close the issue for now as I am unable to provide a code example.
We reverted back to version 12 for now and when I get some downtime at work
I will maybe pull down version 12 and 13 and get some performance metrics.

**Comment by stakx** [comment]
Thanks for your reply. OK, I'll close this for the time being, feel free to add a test case / repro code anytime and we can reopen this issue.

> mocking a large COM Interop object

If you're mocking a co-class, and it's large (as in: it has many virtual methods), that might be the problem. If you're mocking COM interfaces, I'm surprised that updating to the latest Moq version doesn't bring a huge performance speedup as there has been a significant optimization for interface proxies in DynamicProxy recently.

Looking forward to the test code... but take all the time you need.
