### ISSUE TITLE
Question: SetupSequence

### ISSUE THREAD

**Issue by diogonborges** [devlooped/moq#1270]
Is there an option to use SetupSequence in a form that you setup the first, second, and _then_ all subsequent iterations?

```
service.SetupSequence(x => x.Method())
            .Returns(true)
            .Returns(false)
            .ThenReturnForAllOtherIterations(true);
```

**Comment by stakx** [comment]
No, not at this time. There has been a discussion about extending `.SetupSequence` so you can give it an enumerable and it'll return one element from that per call (and something similar would have to exist for `.Callback` of course), but that hasn't been implemented so far.

It used to be possible to add a base "tail" setup first, and then a sequence setup on top of that only for the first few "head" iterations. This setup would then deactivate itself once exhausted. But that behavior changed sometime in the past, so this approach no longer works today. The sequence setup will simply start producing default return values using the default value provider configured.

So in closing, the easiest thing to do is probably to implement your own sequence setup:

```csharp
int i = 0;
mock.Setup(...).Callback(() =>  // or .Returns(...)
{
    switch (i++)
    {
        case 0: ... // first call
        case 1: ... // second call
        default: ... // later calls
    }
});
```
