### ISSUE TITLE
Setup of a property that's overridden

### ISSUE THREAD

**Issue by maxxie85** [devlooped/moq#1284]
When mocking an interface that's derived from a base interface that implements property overrides. The setup of the properties doesn't propagate to the base interface. This sort of makes sense, but I found no way of setting up the base property get.

Consider the following:
``` C#
public interface IBaseInterface
{
    string ValueString { get; }
}
```

``` C#
public interface ISecondInterface : IBaseInterface
{
    new string ValueString { get; }
}
```

``` C#
public class MoqTestProgram
{
    private Mock<ISecondInterface> _mock;

    public MoqTestProgram()
    {
        _mock = new Mock<ISecondInterface>();
        _mock.SetupGet(x => x.ValueString).Returns("HELLO");
    } 
    
    public void Run()
    {
        var foo = _mock.Object;
        
        if((foo as IBaseInterface).ValueString != foo.ValueString)
        {
            throw new Exception();
        }
    }
}
```

This will throw when running the test program. The legitimacy of the need to use the new keyword in the second interface can also be discussed. Unfortunately I need to use a library that does this, and I need to mock an interface from that library that's implemented this way.

**Comment by stakx** [comment]
> The setup of the properties doesn't propagate to the base interface.

And it shouldn't, since those are two entirely separate properties. They only happen to share the same name.

> I found no way of setting up the base property get.

Two things that may be worth trying:

* `mock.SetupGet(m => ((IBaseInterface)m).ValueString)...`
* `mock.As<IBaseInterface>().SetupGet(m => m.ValueString)...`

**Comment by maxxie85** [comment]
> And it shouldn't, since those are two entirely separate properties. They only happen to share the same name.

I agree

> Two things that may be worth trying:
> `mock.SetupGet(m => ((IBaseInterface)m).ValueString)...`

This causes an Unsupported ArgumentException

```
System.ArgumentException: Unsupported expression: (IBaseInterface)x
   at Moq.ExpressionExtensions.Split(LambdaExpression expression, Boolean allowNonOverridableLastProperty) in C:\projects\moq4\src\Moq\ExpressionExtensions.cs:line 159
   at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`4 setupLast, Boolean allowNonOverridableLastProperty) in C:\projects\moq4\src\Moq\Mock.cs:line 643
   at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition) in C:\projects\moq4\src\Moq\Mock.cs:line 498
   at Moq.Mock.SetupGet(Mock mock, LambdaExpression expression, Condition condition) in C:\projects\moq4\src\Moq\Mock.cs:line 516
   at Moq.Mock`1.SetupGet[TProperty](Expression`1 expression) in C:\projects\moq4\src\Moq\Mock`1.cs:line 473
```

The same is true for `(x as IBaseInterface).ValueString`

> `mock.As<IBaseInterface>().SetupGet(m => m.ValueString)...`

This does work! Thanks for the quick response.
