### ISSUE TITLE
Moq fails when a method with input parameter of type Expression<Func<T,bool>> is called

### ISSUE THREAD

**Issue by Arulselvan2408** [devlooped/moq#1288]
When a method with input parameters of type Expression<Func<T,bool>>, the mock setup is not returning the expected value when called inside using statement with transaction inside the using statement.
Let' say my expression is x=>x.Userid==userid where userid is an input parameter of the test method

mock.SetUp(x=>x.SearchFor(expression)).Returns(some expected value).Callback(()=>++counter)

This setup works outside the transaction scope and increases the callback but when I call inside the transaction it do not increase the callback. Upon Debugging when I call inside the transaction the expression value changes to {(t.UserId == value( DisplayClass29_1).**CS$<>8__locals1**.userId)}

here .**CS$<>8__locals1** is added extra to the expression.

FYR
When I call the same method outside transaction {(t.UserId == value(DisplayClass29_0).userId)} looks like this

**Comment by stakx** [comment]
Closing this issue since no repro code was provided. @Arulselvan2408, if you do have (minimally complete) repro code, please post it and I'll take another look.
