### ISSUE TITLE
Moq 4.18.3 Release still pending

### ISSUE THREAD

**Issue by THQ-WIFA** [devlooped/moq#1302]
Since Aug 2022, "SetupAllProperties()" is broken in the current NuGet package Moq 4.18.2, despite the fix is here (see #1278).
The Milestone for 4.18.3 has no other open issue.

I would like to propose that 4.18.3 be released, or scheduled at least.

Regarding the [guidelines](https://github.com/moq/moq4/blob/423fee7c7a7b131ebbe3e59044c9a1ce525a1d57/CONTRIBUTING.md): This is not an API change to v4. This is "bug fixing" and "seems generally useful" to me.

**Comment by stakx** [comment]
I've pushed that one bugfix to NuGet as version 4.18.3... it should become available shortly.
