### ISSUE TITLE
Invocation count incorrect. Argument object is stored as reference and is changed incorrectly

### ISSUE THREAD

**Issue by rufusz** [devlooped/moq#1309]
Invocation.Arguments object is stored as reference and will be changed for all invocations incorrectly.

See here: https://stackoverflow.com/questions/74743085/moq-invocation-arguments-changing-in-subsequent-calls

**Comment by stakx** [comment]
> is stored as reference

... because its type is a reference type, so that is to be expected.

**Comment by stakx** [comment]
If anyone finds this issue and is experiencing the same problem, please see #1319; the last code example in the PR description shows a way how to solve this.
