### ISSUE TITLE
Verifying a protected generic method that returns a value is broken

### ISSUE THREAD

**Issue by nthornton2010** [devlooped/moq#1314]
This Verify method does not pass genericTypeArguments into InternalVerify, so this method will always throw an error because it thinks no generic type arguments were provided even though they were.

https://github.com/moq/moq4/blob/d535cc40870362f9667b64de1308fda3c204e6b8/src/Moq/Protected/ProtectedMock.cs#L253

**Comment by stakx** [comment]
Nice find @nthornton2010. Would you like to submit a PR to fix this?
