### ISSUE TITLE
Verify evaluates the same object  on reuse

### ISSUE THREAD

**Issue by lund76** [devlooped/moq#1316]
Hi

It was really hard to come up with a descriptive title, so right of the bat .. sorry for that.

But I've come across something that I'm not sure is a bug, or by design. But until I broke it down into a smaller example, I was quite sure it was a bug.

I've created a repo with democode:
https://github.com/lund76/MoqMyWords

My mockup has a method that clearly has an error (it's not supposed to update all 3) :
```  Csharp
public class PriceService
{
    private readonly IInventoryService _inventoryService;

    public PriceService(IInventoryService inventoryService)
    {
        _inventoryService = inventoryService;
    }

    public async Task<Product> UpdateOnlyNewestPrice(List<Product> products)
    {
        foreach (var p in products.OrderByDescending(o => o.Created).Take(3))
        {
            await _inventoryService.UpdateAsync(p);
        }
        return products.FirstOrDefault() ?? new Product();
    }
}
``` 

And my test (verify a little funny formed to showcase this issue)
```  Csharp        
[Fact]
public async Task MoqMyWord_UpdateService_OnlyCalledOnce()
{

    var productList = new List<Product>
    {
        new() { Price = 1, Created = DateTime.UtcNow.AddDays(-1) },
        new() { Price = 2, Created = DateTime.UtcNow.AddDays(-2) },
        new() { Price = 3, Created = DateTime.UtcNow.AddDays(-3) }
    };

    Mock<IInventoryService> service = new Mock<IInventoryService>();

    var priceService = new PriceService(service.Object);

    await priceService.UpdateOnlyNewestPrice(productList);

    //For the sake of the argument a silly way to evaluate any price less than 3 is valid
    //This is only to make sure the test fails.
    service.Verify(u => u.UpdateAsync(It.Is<Product>(p => EvaluatePrice(p))),Times.Once);          
}
private bool EvaluatePrice(Product product)
{
    _outputHelper.WriteLine($"product price is {product.Price}");
    return product.Price < 3;
}
```
**This test fails as expected**, since the service is called 2 times:
![image](https://user-images.githubusercontent.com/13216252/210049926-7e21b28a-7456-4c00-9dcd-0f40e9f772cb.png)

If I then make a shitty change to the implementation, and only change a property of an existing object:
![image](https://user-images.githubusercontent.com/13216252/210049525-59b81eb6-1f22-4d37-a4f4-afa481ee440b.png)

I would still expect it to fail with 2 calls to the service, but it fails with no calls to the service. Moq doesn't recognize the change in the object
![image](https://user-images.githubusercontent.com/13216252/210050410-58ee830b-c80a-4b79-8554-51ffa6855033.png)

**Comment by stakx** [comment]
Hi @lund76, no worries about the issue title, it's actually quite acurate. This question gets asked _a lot_ (recently e.g. in #1309 and #1187). When Moq records invocations (for later verification), it simply captures the invocation arguments in an `object[]` array &ndash; it does **not** deep-clone every argument. This means that the usual .NET rules apply: reference types (such as your `Product` class) are captured by reference, and value types are captured by value (which essentially amounts to a shallow clone). Therefore if the same `Product` is captured on three invocations, and you change that `Product` instance over time, this will be reflected in the recorded invocations.

I'm a little early, but... have a happy new year! 🎆

**Comment by lund76** [comment]
Thanks for the reply. It what pretty sure it was something along those lines. 
I've tried searching a bit for the issue, but must have given up to quickly - sorry for that :) 

Have a happy new year as well :)

**Comment by stakx** [comment]
FYI @lund76, I'm likely going to merge #1319 which will provide a new way to solve this issue; see the last code example in the PR's description for an explanation of how this might help.
