### ISSUE TITLE
Question: Using local variables in .Returns()

### ISSUE THREAD

**Issue by m-redding** [devlooped/moq#1321]
I am mocking a public class that has an internal type. The public class has asynchronous getters/setters that are used to access the getters/setters of the internal type. I am trying to mock a getter/setter pair:
```csharp
// local variable defined in the test method
var mockFakeValue = new BinaryData("NotSet");

mockClass
    .Setup(c => c.FakeSetterAsync(It.IsAny<BinaryData>(), It.IsAny<CancellationToken>())
    .Callback<BinaryData, CancellationToken>((val, ct) => mockFakeValue = val);

mockClass
    .Setup(c=>c.FakeGetterAsync(It.IsAny<CancellationToken>())
    .Returns(Task.Run(() => mockFakeValue);

CancellationTokenSource cts = new();
BinaryData newValue = new("SetValue");

await mockClass.Object.FakeSetterAsync(newValue, cts.Token);
BinaryData updatedValue = await mockClass.Object.FakeGetterAsync(cts.Token);
```

After executing this code, mockFakeValue is equal to "SetValue" but updatedValue is equal to "NotSet". I also tried using a callback rather than .Returns(Task.Run(...)) but I was seeing the same issue there as well.

**Comment by stakx** [comment]
My first guess would be to fix one obvious mistake:

```diff
-.Returns(      Task.Run(() => mockFakeValue);
+.Returns(() => Task.Run(() => mockFakeValue);
```

Otherwise you're starting that task right away (while you're setting up your mock) and each invocation will return that same task. It will run concurrently with the remainder of your code, so you could potentially end up with a race condition.

The `() =>` means that the return value will only be computed on invocation, and you'll get a new, separate task for each invocation.

**Comment by m-redding** [comment]
Doing something similar to that ended up working for me, thank you! I think I got confused because using that syntax in `.Callback` didn't work for me.

**Comment by stakx** [comment]
FYI here are some other syntaxes you can use to set up the return value of an async method that don't require you to explicitly start a task:

1. `.Setup(m => m.BlahAsync()).ReturnsAsync(value)`
2. `.Setup(m => m.BlahAsync()).Returns(async () => value)`
3. `.Setup(m => m.BlahAsync().Result).Returns(value)`

At this time, it's mostly a matter of personal preference which one you use.
