### ISSUE TITLE
Add/support Target Framework net7.0

### ISSUE THREAD

**Issue by Adam-S-Daniel** [devlooped/moq#1327]

**Comment by stakx** [comment]
We already target `net6.0`, which should be perfectly sufficient for .NET 7 projects. Can you explain what benefit you expect from a separate `net7.0` TFM?

**Comment by stakx** [comment]
I did some quick research. Not even the official `System.*` packages target both `net6.0` and `net7.0` but just the former.

As far as I can tell, having a `net7.0` target would be completely redundant.
