### ISSUE TITLE
Proper usage of It.IsAnyType

### ISSUE THREAD

**Issue by marbletravis** [devlooped/moq#1329]
I am using It.IsAnyType, but its not working now I think it should, based on the documentation. 

```
FakeMediator.Setup(x => x.Send(It.IsAny<It.IsAnyType>(), It.IsAny<CancellationToken>())).ReturnsAsync(true); //Does Not Work
FakeMediator.Setup(x => x.Send(It.IsAny<Request>(), It.IsAny<CancellationToken>())).ReturnsAsync(true); // Works
```

I think I am doing it right, based on the documentation.

I am on version 4.18.4

I don't get any exceptions, just that the first one doesn't match, the second one does.

Here is the line in the documentation I am trying to follow
```
mock.Setup(m => m.M2(It.IsAny<It.IsAnyType>())).Returns(true);
```

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by stakx** [comment]
I've noticed that people tend to overuse `It.IsAnyType`. You can often just use `object` instead.

Without repro code, it's hard to judge what you're doing right or wrong. Please provide a minimal, runnable, verifiable code example.

**Comment by marbletravis** [comment]
@stakx does this help?

```
using MediatR;
using Moq;
using Xunit;

namespace Moq;

public class MoqTests
{
	[Fact]
	public async Task Test_Works()
	{
		var moq = new Mock<IMediator>();

		moq.Setup(x => x.Send(It.IsAny<TestRequest>(), It.IsAny<CancellationToken>())).ReturnsAsync(true);

		var result = await moq.Object.Send(new TestRequest());

		Assert.True(result);
	}

	[Fact]
	public async Task Test_Fails()
	{
		var moq = new Mock<IMediator>();

		moq.Setup(x => x.Send(It.IsAny<It.IsAnyType>(), It.IsAny<CancellationToken>())).ReturnsAsync(true);

		var result = await moq.Object.Send(new TestRequest());

		Assert.True(result);
	}

	[Fact]
	public async Task Test_AlsoFails()
	{
		var moq = new Mock<IMediator>();

		moq.Setup(x => x.Send(It.IsAny<object>(), It.IsAny<CancellationToken>())).ReturnsAsync(true);

		var result = await moq.Object.Send(new TestRequest());

		Assert.True(result);
	}

	public class TestRequest : IRequest<bool> { }
}
```

**Comment by Simoris** [comment]
I don't think this is a bug. The mediator interface contains multipleoverloads of the `Send`-Method, including one accepting TRequest and one accepting any object. The MediatR-implementation of this interface then tries to cast the object-argument to some fitting `IRequest` - but Moq can't see or use any of this.
To Moq `Send(object ...)` and `Send(Request ...)` are to different methods, even if MediatR wants them to be connected. You're always calling the latter, but in your Failure-Cases mocking the first one.

Such problems sometimes can be avoided by keeping the interface itself small and shifting trivial overloads to extension-methods, but the MediatR version does seem to require some more work for the overload (and you probably have no control over it anyway).
