### ISSUE TITLE
Issue with multiple identical setups

### ISSUE THREAD

**Issue by koder-man** [devlooped/moq#1330]
Seen with 4.18.1.

Suppose we have this interface:
```
public interface ISample
{
    void Mock(object fi);
}
```

And the following code:
```
var mock = new Mock<ISample>();
mock.Setup(x => x.Execute(It.Is<object>(_ => true))).Verifiable();

var flag = true;
mock.Setup(x => x.Execute(It.Is<object>(_ => flag))).Verifiable();

mock.Object.Execute(new object());

mock.Verify();
```

Calling to `mock.Verify()`:
- Expected behaviour: call succeeds (behaviour in 4.18.0 and before).
- Actual behaviour: call fails with error:
```
This mock failed verification due to the following:

MockSetupTests.ISample x => x.Execute(It.Is<object>(_ => True)):
This setup was not matched.
```

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by stakx** [comment]
Except those setups aren't truly identical. The question here is when captured variables should be resolved to their values: at the time when the setup is created vs. when an invocation happens that could match the setup.

There have been a few recent changes to this, so not sure we can go back to the previous behavior in your precise use case... but I'll look into it.
