### ISSUE TITLE
More of a query than an issue: Can Moq support mocking a managed C++ class called from C# code?

### ISSUE THREAD

**Issue by Vijayendar** [devlooped/moq#1335]
Hello Moq Team,

I am trying to use Moq to mock a managed C++ class called from within C# code, using the standard way described (Instantiating an interface present in c++ to the Moq class, making the c++ method virtual, ...). But none of these seem to work. If I pass the interface, I get a System.runtime exception that says the method has not been implemented. It definitely has an implementation. 

If I pass the concrete Class type to Moq<>, and specify the parameters of the method to be mocked in the Setup() call, the actual method is called, even though it is specified as virtual. Meaning no mocking is happening. 

I am afraid I can't share the actual code to reproduce the problem, but I can create sample code to reproduce a working example, if needed. My question is: Can Moq even support such behaviour (Mocking a managed C++ class/interface from within C#)?

Thanks in advance.

**Comment by stakx** [comment]
As far as I am aware, support for C++/CLI, or Managed C++, was not an explicit design goal of Moq, nor of DynamicProxy (the proxying library upon which Moq up to v4 is built), so I guess the answer will be: if it works, it works; if not, too bad. I further suspect that support for C++ language constructs generally won't be that good: for example, DynamicProxy doesn't have any logic to handle pointer-typed arguments. Also, Managed C++ makes use of so-called "modreqs" at the CLI metadata level, and those aren't well-supported by .NET Reflection... all things considered, I wouldn't hold my breath if I were you.

**Comment by stakx** [comment]
@Vijayendar, I am going to close this issue, I am assuming that your question has been answered. If not, let me know what needs to be clarified further.
