### ISSUE TITLE
Mocking derived classes of Exception results in .Object being null

### ISSUE THREAD

**Issue by KWodarczyk** [devlooped/moq#1337]
```
    public class myClass : Exception
    {

    }
```
```

            var obj = new Mock<myClass>().Object;// obj will be null why ?
```

**Comment by stakx** [comment]
I cannot reproduce this problem.

```csharp
using System;
using Moq;

Console.WriteLine(new Mock<myClass>().Object is Exception);  // outputs "True"

public class myClass : Exception { }
```

Everything works as it should, at least with the current version of Moq (4.18.4).

Btw. do you even need to mock `Exception`? Or could you perhaps just... instantiate one using `new`?

**Comment by KWodarczyk** [comment]
What happens if you remove "is Exception" btw I'm using windows apps SDK and .net 6
Also assign it to var first as I did

**Comment by stakx** [comment]
You can try that yourself.

But I guess the problem doesn't lie with the code itself, but with the targeted platform. I don't know Windows App SDK (Microsoft keeps releasing a new app platform SDK once every two years or so, I've given up trying to keep up), any chance your code gets compiled ahead-of-time (AOT) / compiled to native code / Ready-to-Run (R2R) / whatever else it's called these days?

If so, you're out of luck as Moq v4 & DynamicProxy, the library it's based on, heavily relies on Reflection, which may not be fully supported when compiling to native code.

**Comment by stakx** [comment]
@KWodarczyk, I am going to close this issue due to missing repro code. If you want this to be looked into any further, please provide instructions how to reliably repro this issue and we can reopen.
