### ISSUE TITLE
Can't mock a method with generic parameter and new() constraint C# Framework 4.8

### ISSUE THREAD

**Issue by Matt-at-Hyland** [devlooped/moq#1338]
```
public class DataType
{
}
public interface IRepository
{
    bool BulkInsert<T>(IEnumerable<T> objects) where T : DataType, new();
}

Mock<IRepository> mockObject = new();

mockObject.Setup(m =>
    m.BulkInsert(
	    It.Is<IEnumerable<DataType>>(t => t != null && t.GetType().GetConstructor(Type.EmptyTypes) != null))
    .Returns(null);
``` 
  
This returns:
CS0310	'DataType' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'IRepository.BulkInsert<T>(IEnumerable<T>)'

**Comment by stakx** [comment]
This is a C# compiler error which has nothing to do with Moq. Closing.

**Comment by Matt-at-Hyland** [comment]
So is there not a way to mock this method?
