### ISSUE TITLE
Thread Safety issue in Moq reported by Infer# report

### ISSUE THREAD

**Issue by IngawaAb-bh** [devlooped/moq#1347]
C:/projects/moq4/src/Moq/SetupCollection.cs:107: warning: Thread Safety Violation
  Read/Write race. Non-private method `SetupCollection.FindLast(...)` reads without synchronization from container `this.Moq.SetupCollection.setups` via call to `List`1<!0>.get_Count()`. Potentially races with write in method `SetupCollection.Clear()`.
 Reporting because this access may occur on a background thread.

**Comment by stakx** [comment]
This is technically correct, but it really shouldn't matter as it's only a fast-path optimization.
