### ISSUE TITLE
Missing License Information In Nuget metadata

### ISSUE THREAD

**Issue by LiorBanai** [devlooped/moq#1348]
Hi,
Could the MIT license information be added to the nuget information?
it is good to add it so it will be shown in Visual Studio nuget management.

example:

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

Also some tools can create auto generated report like (dotnet-project-licenses)  but right now those create missing entry:

![image](https://github.com/moq/moq/assets/36262995/1fdde0db-badd-45cd-8bba-ce6f8a3a7c62)

**Comment by stakx** [comment]
I'm experiencing a déjà vu moment, aren't we doing this already?

https://github.com/moq/moq/blob/02b798af2295c4dfc54bc51cb92199d7c52ec3ff/src/Moq/Moq.csproj#L36

**Comment by LiorBanai** [comment]
Interesting. 
 The verion on nuget if from 7 months ago 
![image](https://github.com/moq/moq/assets/36262995/9b7f738b-71a5-463b-82f5-a441d35604c9)

while the commit is from 6 months ago:
![image](https://github.com/moq/moq/assets/36262995/a78a8d68-da23-46c7-9f1b-39ecc88cb23f)

**Comment by stakx** [comment]
Ah, you're right of course, thanks. I can't believe it's been that long since the last release. About time we published v.4.19.0.
