### ISSUE TITLE
Documentation link in readme is broken

### ISSUE THREAD

**Issue by andrewlangemann** [devlooped/moq#1349]
The documentation link in the readme ([http://moq.github.io/moq4/](http://moq.github.io/moq4/)) takes me to a 404 error page: 
![image](https://github.com/moq/moq/assets/26331901/f6454fe8-c45c-435f-85ef-47a7f3973821)

**Comment by stakx** [comment]
Hmm. I suppose this happened when this repository was renamed from its earlier name moq/moq4. I'm going to contact @kzu about this anyways, will ask whether we can restore the documentation page, too (even though it didn't have any actual content just yet).

**Comment by kzu** [comment]
Yeah, I figured there's no need to keep the 4 suffix anymore. I've renamed the other repo vnext to make it more obvious.
