### ISSUE TITLE
Upgrading to version 4.20.1 breaks the build

### ISSUE THREAD

**Issue by spewu** [devlooped/moq#1371]
Hi there

I just upgraded our solution to the latest version of Moq (v. 4.20.1), and now all of our test projects fail to build on my Mac. I get this exception:

`Analyzer 'Moq.SponsorLinker' threw an exception of type 'System.UnauthorizedAccessException' with message 'Access to the path '/usr/local/share/dotnet/sdk/7.0.302/Roslyn/bincore/%TEMP%\1M5Ot' is denied.'.`

Looks like this was made for Windows, as `%TEMP%` looks like a Windows environment variable, which does not work on macOS.

Have to downgrade to 4.18.4 to get the build working again.

Hope you can look into this 🙂

**Comment by cimnine** [comment]
My team and I have the same. It seems related to #1363. Though it does not _break the build_ because it's just a warning, it creates unnecessary files and creates unnecessary build warnings. So if you're like our team and fail a build when there's a build warning, Sponsorlink effectively breaks the build.

**Comment by stand-sure** [comment]
it is also creating rogue files/directories on macos, to wit: "%TEMP%\\1M5Ot/"

**Comment by Porkechebure** [comment]
Do not restore anything, let this horrible spaghetti code die. It's been around for too much

**Comment by kzu** [comment]
Uh... that's weird. I'm pretty sure I tested it on Linux and it worked, assumed it would on MacOS. I'll revert it. This is a blocker.

**Comment by ccremer** [comment]
Just to be precise: It also breaks on my Linux (Mint/Ubuntu), with rogue files in `%TEMP%\\1M5Ot`. So not just MacOs ;)

**Comment by kzu** [comment]
Dang, Linux too?! I guess WSL lied to me then, he.
