### ISSUE TITLE
Change log is not updated since version 4.18.4

### ISSUE THREAD

**Issue by abatishchev** [devlooped/moq#1406]
The last record at [CHANGELOG.md](https://github.com/moq/moq/blob/main/CHANGELOG.md) is for version `4.18.4 (2022-12-30)`.

I wonder if this is intentional or not, and also what has changed since. @kzu, can you please fill it in?

**Comment by kzu** [comment]
It was previously manually updated by @stakx. I do automated changelog in all my repos, but I just noticed that even if the action run green there was an error when updating from the GH action: https://github.com/moq/moq/actions/runs/5836450586/job/15830043450

![image](https://github.com/moq/moq/assets/169707/24eaecbe-bf09-4938-a811-5d18cd0b2fd6)

Checking why that didn't commit... Thanks for reporting!

**Comment by stakx** [comment]
> It was previously manually updated by @stakx.

In fact it was expanded by whomever submitted relevant code changes. I only updated the "Unreleased" headers with version numbers immediately prior to a new release.

I'm curious though, how does your automated changelog creation process work? Is it based on the titles and authors of issues & PRs that went into a release?

(The reason why I thought that a manually edited file was OK was that issue & PR titles often aren't the best possible summary for a bug or change (from a user perspective), and sometimes you may want to add some additional notes that couldn't be derived from them. Also, not all issues and PRs may be significant, so manually deciding to omit some them may remove some noise from the log.)

**Comment by kzu** [comment]
It uses a [config file](https://github.com/moq/moq/blob/main/.github/workflows/changelog.config) and the [github changelog generator](https://github.com/moq/moq/blob/main/.github/workflows/changelog.yml#L34). 

So, labels become important, as well as PR titles. Once you factor in this fact, what I usually do is amend PR titles with that in mind. 

While the changelog is fully automated, the release notes aren't. That uses GH's built-in button to generate the release notes while you create a release from [its own config](https://github.com/moq/moq/blob/main/.github/release.yml) which is very very close to the changelog generator itself. This feature came a bit after I started doing the automated changelog generation, so perhaps I should invest some time in unifying them so the direct notes from the actual release (potentially manually tweaked) make it to the changelog.md as-is. But right now, that's the mix.
