### ISSUE TITLE
SponsorLink Integration Makes Moq Unuasable due to PII and GDPR Requirements

### ISSUE THREAD

**Issue by bleepzter** [devlooped/moq#1433]
Based on the comments of DinglDanglBob in the r/dotnet channel - it seems like "starting from version 4.20, does include a .NET analyzer that scans your local git config on build, gets your email address and sends it to some service hosted in Azure to check whether or not you're a sponsor."

This is unacceptable for medical, scientific, and financial organizations that work with PII (Personally Identifiable Information) and payment information and are regulated under PCI DSS, HIPPA, CCPA, or GDPR.

**Comment by bleepzter** [comment]
It was closed long ago, but it still removes the library from the list of acceptable use OSS due to this issue. It can no longer be trusted.

**Comment by zarlo** [comment]
okay and what is your point making this issue?

**Comment by Laurianti** [comment]
https://github.com/devlooped/moq/commit/6f3cf622ea8713757883d957313c6ad3aa5a1fb7

Has this change been released?

**Comment by kzu** [comment]
![image](https://github.com/devlooped/moq/assets/169707/c733dee1-ca6d-4403-a9e1-a7393dc14e46)

**Comment by Laurianti** [comment]
![image](https://github.com/devlooped/moq/assets/20415513/1bb6dc83-e642-4bd6-a6a9-211592885003)

Yes, it's finally resolved. Unlike v4.20.69, the issue is fixed in v4.20.70, which was released on November 28.

**Comment by eduvhc** [comment]
After the widespread adoption of NSubstitute, it became clear that efforts to monetize a popular and community-supported open source library could contribute to its decline. In essence, NSubstitute has now become the go-to choice for companies.

**Comment by Laurianti** [comment]
Why do you say this? Hasn't the issue been resolved? Are there still reasons not to use Moq today?

**Comment by Laurianti** [comment]
> After the widespread adoption of NSubstitute, it became clear that efforts to monetize a popular and community-supported open source library could contribute to its decline. In essence, NSubstitute has now become the go-to choice for companies.

Why do you say this? Hasn't the issue been resolved? Are there still reasons not to use Moq today?

**Comment by MichaMican** [comment]
@Laurianti - it is not gone for good - it was first removed due to moq breaking on MacOS -> https://github.com/devlooped/moq/pull/1375

Also the big Discussion thread (https://github.com/devlooped/moq/issues/1374) doesn't change in a commitive end that this will not happen again. They just want to "find a better way" to do it with (hopefully) the feedback from the poll (https://github.com/devlooped/moq/discussions/1414)

Even though it's fine now - there is no clear commitment of ditching the SponsorLink concept and only time will tell when and how it will return

**Comment by kzu** [comment]
It will not come back with any PII or GDPR issues. Please read about the new approach and provide feedback at https://github.com/devlooped/SponsorLink/issues/100
