### ISSUE TITLE
Wrong Setup by using String interpolation within It.Is<string>

### ISSUE THREAD

**Issue by albmargu** [devlooped/moq#1439]
I upgraded Moq package from 4.16.1 to 4.20.69
I also use the latest .NET test packages under Visual Studio 2022

The setup for the _mockWebService is:
```c#
protected Mock<BaseWebService> _mockWebService;

public async Task SetupTest()
{
	_mockWebService = new Mock<Network.BaseWebService>(MockBehavior.Strict);
	var controllers = new List<string>()
	{
		"User",
		"Configuration",
	};
	foreach (var controller in controllers)
		_mockWebService.Setup(x => x.HttpGet<bool>(It.Is<string>(url => url.Contains($"{controller}/")))).ReturnsAsync(false);
}
```

This code was working well, but is failing now:
```c#
Moq.MockException: Mock<BaseWebService:102>:
This mock failed verification due to the following:

   BaseWebService x => x.HttpGet<bool>(It.Is<string>(url => url.Contains(string.Format("{0}/", controller)))):
   This setup was not matched.
```
The bypass for me was changing the previous foreach into this:
```c#
_mockWebService.Setup(x => x.HttpGet<bool>(It.Is<string>(url => url.Contains("User/", StringComparison.OrdinalIgnoreCase)))).ReturnsAsync(false);
_mockWebService.Setup(x => x.HttpGet<bool>(It.Is<string>(url => url.Contains("Configuration/", StringComparison.OrdinalIgnoreCase)))).ReturnsAsync(false);
```
Should I avoid string interpolation at all in this case?

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by ShirAvneri** [comment]
I noticed you only specify `StringComparison.OrdinalIgnoreCase` in your bypass.
Have you tried adding it to the foreach as well?

**Comment by albmargu** [comment]
No, I didn't.
I noticed in the Stack Trace that the string interpolation is converted in to String.Format(). I should try to use it and check it

**Comment by ShirAvneri** [comment]
> No, I didn't. I noticed in the Stack Trace that the string interpolation is converted in to String.Format(). I should try to use it and check it

When I ran it locally, it worked as expected, i.e. for https://some-url.com/user/123, the test failed and for https://some-url.com/User/123, the test passed.

Perhaps the following would be more appropriate:
`_mockWebService.Setup(x => x.HttpGet<bool>(It.IsRegex($"{controller}/", RegexOptions.IgnoreCase))).ReturnsAsync(false);`

**Comment by albmargu** [comment]
> > No, I didn't. I noticed in the Stack Trace that the string interpolation is converted in to String.Format(). I should try to use it and check it
> 
> When I ran it locally, it worked as expected, i.e. for https://some-url.com/user/123, the test failed and for https://some-url.com/User/123, the test passed.
> 
> Perhaps the following would be more appropriate: `_mockWebService.Setup(x => x.HttpGet<bool>(It.IsRegex($"{controller}/", RegexOptions.IgnoreCase))).ReturnsAsync(false);`

You are right, but it worked as is in the previous release.
