### ISSUE TITLE
Supporting .NET8

### ISSUE THREAD

**Issue by geraldbauer** [devlooped/moq#1462]
We are creating .NET 8 applications and wondered when/if Moq will support .NET 8.

**Comment by JasonLandbridge** [comment]
I can confirm Moq 4.20.70 works with .NET 8. I just ran 152 unit tests and 24 integration tests without problems

**Comment by NikoUmbleLSPA** [comment]
> I can confirm Moq 4.20.70 works with .NET 8. I just ran 152 unit tests and 24 integration tests without problems

So then, did you do something to overcome this kind of error?:

> Unable to resolve 'Moq (>= 4.20.70)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: Microsoft Visual Studio Offline Packages, nuget.org.

**Comment by kzu** [comment]
Yep, that was kinda expected. .NET has a great backs-compat track record 👏
