### ISSUE TITLE
Documentation Unavailable Online

### ISSUE THREAD

**Issue by grantwforsythe** [devlooped/moq#1473]
## Describe the Bug

The website referenced in the README, https://moq.github.io/moq/, is returning a 404.

Checking [other deployments](https://github.com/devlooped/moq/deployments), the most recent one was over 5 months ago to https://www.devlooped.com/moq/ which is still under construction.

Is the documentation hosted somewhere else?

**Comment by kzu** [comment]
The best documentation for moq is everywhere on the web. Stackoverflow is full of answers related to Moq.

It's unlikely you'll see official docs at this point beyond the quickstart, unless someone with docs writing chops can contribute. 

vNext might be different in this regard.

**Comment by kzu** [comment]
Removed link and badge for now
