### ISSUE TITLE
Constructor arguments should be nullable

### ISSUE THREAD

**Issue by qrjo** [devlooped/moq#1494]
The constructor arguments that are passed to a mocked class' constructor are now typed as `object[]`, this causes a lot of unwarranted warnings when passing null, because the mocked class in question might actually allow null for its arguments. The type should be changed to `object?[]`.

I'm running into this problem when constructing Mock<T>:
```csharp
public Mock(params object[] args)
public Mock(MockBehavior behavior, params object[] args)
```

These should be changed to:
```csharp
public Mock(params object?[] args)
public Mock(MockBehavior behavior, params object?[] args)
```

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by daCostaeurogard** [comment]
Yes , i encountered the same problem as well see https://developercommunity.visualstudio.com/t/Dot-Net-xunit-test-to-fail-with-exceptio/10713601

But i got Nul  errors, so that he tests failed
