### ISSUE TITLE
Documentation link gives 404

### ISSUE THREAD

**Issue by siva-sankaran** [devlooped/moq#1495]
## Describe the Bug
Link to In-depth documentation in README file under [Where section](https://github.com/devlooped/moq?tab=readme-ov-file#where) is giving 404. I guess it should be pointing to https://moq.github.io/

## Steps to Reproduce
1. Go to Where section of README file https://github.com/devlooped/moq?tab=readme-ov-file#where
2. Navigate to the link provided under link text "documentation website".
3. This will get you to http://moq.github.io/moq/ which is 404 Page not found error page. The Screenshot of the page is below. 
![image](https://github.com/user-attachments/assets/abd8c9bf-37e7-424d-98e8-4f1408fb0b51)

## Expected Behavior
The link for In-depth documentation provided under text "documentation website" should show the home page of https://moq.github.io/
![image](https://github.com/user-attachments/assets/aa53a23d-a2ab-438c-90dd-71e4257a0226)

## Exception with Stack Trace
Not Relevant

## Version Info
Not Relevant

## Additional Info
Not Relevant

**Comment by kzu** [comment]
There's no planned in depth documentation for current v4
