### ISSUE TITLE
Question: Sponsorable Attribute in release v4.20.71

### ISSUE THREAD

**Issue by tomvdk** [devlooped/moq#1513]
Hi @kzu ,

First of all, thank you for your work on Moq.

We've noticed in [release v4.20.71](https://github.com/devlooped/moq/releases/tag/v4.20.71), you've added an attribute **Sponsorable**. This raised a few questions at our company:

1. Could you please explain the intend of this as it appears it is not used anywhere for now?
2. How will you determine or will determine if a user is a sponsor?

[assembly: Sponsorable(60)]
namespace Moq
{
    class SponsorableAttribute : Attribute
    {
        public SponsorableAttribute() { }
        public SponsorableAttribute(int days) { }
    }
}

Thanks for your answers.

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
I have unlisted that version and .72 should be out momentarily without that unused attribute. Thanks for spotting it :)
